// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-6qtjUWLYD9cp68sd2RmrZfy6OT6C0EQ',
    appId: '1:581865118836:web:3d3a5a6cd1b78731b50521',
    messagingSenderId: '581865118836',
    projectId: 'bamboo-clone-375709',
    authDomain: 'bamboo-clone-375709.firebaseapp.com',
    storageBucket: 'bamboo-clone-375709.appspot.com',
    measurementId: 'G-REFN079XDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpeqjtz-Z87Oz83gK6ZWcIL85MpAU7XDw',
    appId: '1:581865118836:android:abfcca36a6d23f53b50521',
    messagingSenderId: '581865118836',
    projectId: 'bamboo-clone-375709',
    storageBucket: 'bamboo-clone-375709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmqlEOoZiwfhdipPWBza2tlb3psfCfIZA',
    appId: '1:581865118836:ios:e3718d2cb801e135b50521',
    messagingSenderId: '581865118836',
    projectId: 'bamboo-clone-375709',
    storageBucket: 'bamboo-clone-375709.appspot.com',
    iosClientId: '581865118836-4tidjev30obcda596jsjnpq0li6l4i3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.awesomeChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmqlEOoZiwfhdipPWBza2tlb3psfCfIZA',
    appId: '1:581865118836:ios:e3718d2cb801e135b50521',
    messagingSenderId: '581865118836',
    projectId: 'bamboo-clone-375709',
    storageBucket: 'bamboo-clone-375709.appspot.com',
    iosClientId: '581865118836-4tidjev30obcda596jsjnpq0li6l4i3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.awesomeChat',
  );
}
